### PR TITLE
Layout content of shortcuts page to include some shortcuts

### PR DESCRIPTION
**Pull request by 2metres**
### Public-Facing Changes
Shortcuts page now contains a list of all shortcuts

### CODE REVIEW

**Comment by 2metres** [comment]
I did this one on the old docs site right before the cut over.

**Comment by esthersweon** [comment]
Headers are not consistent ("shortcuts" or not?)

Screenshot 2024-01-04 at 2 34 41 PM

Full-width tables with inconsistent column widths looks odd - either make uniform or snap to content width (like other tables in docs):

Screenshot 2024-01-04 at 2 34 25 PM

**Comment by 2metres** [comment]
@esthersweon I've made your suggested changes can you take another look?

**Comment by esthersweon** [comment]
Break up into separate tables with their own headers (weird that one header is gray, and the other isn't - these rows aren't on the same hierarchy level):

Screenshot 2024-01-10 at 1 38 40 PM

Have preference for not including "shortcuts" in headers, since it's already the page title.

Missed this the first time, but "Zoom in and out horizontal" should be "Zoom in and out horizontally".

Some rows also have "Zoom in and out" vs. "Zoom in and out both horizontally and vertically" - should be consistent.

**Review by esthersweon — APPROVED** [review]

**Pull request merged**
