### PR TITLE
Clarity around using special characters in event metadata query

### PR DESCRIPTION
**Pull request by wimagguc**
### Changelog

Making it clearer how to use special characters when querying event metadata.

### Description

Our query language requires quotes around special characters, for example, when we want to find an event with the metadata `/joint_states:0` consider these queries:

* `"/joint_states":*` will find the event, but
* `/joint_states:*` will not.

Related small UX improvement in app: https://github.com/foxglove/app/pull/6071

### CODE REVIEW

**Review by mkerpelman — COMMENTED** [review]
@wimagguc should we exhaustively list out what constitutes "special characters", or is that a known label that developers will understand intuitively?

**Comment by jtbandes** [comment]
Are escaped quotes supported inside quotes? 🤔

**Comment by wimagguc** [comment]
> Are escaped quotes supported inside quotes? 🤔

The short answer is that _it should_ and the long is that _it should but doesn't_. I've filed a bug: [FG-7442](https://linear.app/foxglove/issue/FG-7442/device-event-query-search-incorrectly-handles-escaped-quoted-text), thanks for asking!

**Comment by wimagguc** [comment]
> @wimagguc should we exhaustively list out what constitutes "special characters", or is that a known label that developers will understand intuitively?

Thanks @mkerpelman, I've added the complete list to avoid doubt.

**Comment by wimagguc** [comment]
> I might tend to say "non-alphanumeric characters" (even though that's overly conservative) instead of providing an explicit set, to avoid locking us into any implied api contract, but I'm OK either way.

Thanks Bryan, I liked yours more; let's see what @mkerpelman says before merge?

**Pull request merged**
